### ISSUE TITLE
Dragging between Primary and Secondary commands doesn't work

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/studio#57]
### Current behavior

In the Elements tools window, dragging items between the PrimaryCommands and SecondaryCommands doesn't work correctly. 

In this animation:

- I try and move an item from the secondary list to the first, it incorrectly shows it as nested but when the automatic (hot?) reload kicks in the move fails with no warning. 
- I then try and drag (move an item) from the primary to the secondary list and that fails also.

![Image](https://github.com/user-attachments/assets/091a3d44-20ec-4cec-8597-45a034a02010)

### Expected behavior

- Dragging between collections should work.
- Whether something can be dragged should be indicated correctly.
- Errors/failures should be reported somewhere.

### Which tool(s) are affected?

Hot Design™

### Affected platforms

Desktop (Skia)

### Uno.Sdk version

5.6.22

### IDE used

Visual Studio 2022

### IDE version

7.13.0 Preview 5.0

### Uno Platform Extension version

5.6.15.19

### Anything else we need to know?

Originally from #53

**Comment by iurycarlos** [comment]
Hi! 
Thanks @mrlacey !
Issue was already solved by a recent PR. moving to QA.

**Comment by agneszitte** [comment]
Hi @mrlacey!  

Could you let us know if you're still experiencing this issue with the latest **Uno Platform Visual Studio Extension** version [5.6.40.64](https://marketplace.visualstudio.com/items?itemName=unoplatform.uno-platform-addin-2022) and **Uno.Sdk 5.6.45**?  
Thanks! 😊

**Comment by nickrandolph** [comment]
This is still failing in some scenarios eg:
- Create a new app using Blank preset
- Add Toolkit to Features
- Add NavigationBar into Grid by editing XAML before running app
- Run app and enter HD
- Add AppBarButton to PrimaryCommands (use + button on PrimaryCommands node in Elements)
- Add AppBarToggleButton to SecondaryCommands
- Attempt to drag the AppBarToggleButton to the first position of PrimaryCommands
For a split second the AppBarToggleButton appears as a sub-node of the AppBarButton, instead of it's predecessor element
- The drag will be undone
- Attempt the drag again
Error thrown inside VS

Error:
-------------------------------------
03:25:59.23 [Error] Exception while emitting update: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Emit.DefinitionMap.GetPreviousMethodHandle(IMethodSymbolInternal oldMethod, IMethodSymbolInternal& peMethod)
   at Microsoft.CodeAnalysis.Emit.DefinitionMap.GetDeletedSynthesizedMethods(IMethodSymbolInternal oldMethod, ImmutableArray`1 currentLambdas)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.<CreateDeletedMethodsDefs>g__addDeletedClosureMethods|83_2(IMethodSymbolInternal oldMethod, ImmutableArray`1 currentLambdas, ImmutableArray`1 orderedLambdaRuntimeRudeEdits, <>c__DisplayClass83_0&, <>c__DisplayClass83_1&)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.<CreateDeletedMethodsDefs>g__getDeletedMethodDefs|83_1(ITypeDefinition typeDef, <>c__DisplayClass83_0&)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.<CreateDeletedMethodsDefs>g__recurse|83_0(ITypeDefinition typeDef, <>c__DisplayClass83_0&)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.CreateDeletedMethodsDefs(EmitContext context, SymbolChanges changes)
   at Microsoft.CodeAnalysis.Compilation.SerializeToDeltaStreams(CommonPEModuleBuilder moduleBeingBuilt, DefinitionMap definitionMap, SymbolChanges changes, Stream metadataStream, Stream ilStream, Stream pdbStream, ArrayBuilder`1 updatedMethods, ArrayBuilder`1 changedTypes, DiagnosticBag diagnostics, Func`2 testSymWriterFactory, String pdbFilePath, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(CSharpCompilation compilation, EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, UpdateId updateId, CancellationToken cancellationToken)
03:25:59.23 [Error] C:\temp\QAReviewBlankApp2\QAReviewBlankApp2.sln (line 1): error ENC1002: Cannot apply changes -- unexpected error: 'Object reference not set to an instance of an object.'
03:25:59.23 Invalid changes were found. Please refer to the Error List window to fix those issues.
-------------------------------------



![Image](https://github.com/user-attachments/assets/29f7c187-4853-4b0d-9413-72867ac742aa)

cc @carldebilly

**Comment by nickrandolph** [comment]
Repro: 
- Make sure application is referencing Toolkit (by adding Toolkit to UnoFeatures in csproj)
- Drag NavigationBar onto page
- Add a PrimaryCommand (use the + button on PrimaryCommands in the Elements)
- Drag the newly created command from PrimaryCommands to SecondaryCommands

**Comment by carldebilly** [comment]
That's a Hot Reload issue

**Comment by jhanvi03** [comment]
Initially, I was able to add a PrimaryCommand using the "+" button and drag it between the Primary and SecondaryCommands without any issues.

However, on the second attempt:
- The HR indicator displayed the message:
"Could not save updated XAML content to disk. Error: Unable to save 'D:/VSProjects/UnoApp51/UnoApp51/Presentation/MainPage.xaml'"

- After this error, the application got stuck in the "Updating..." state and didn’t recover.

Tested with:
sdk/template: 6.2.0-dev.53
HD version: 1.15.0-dev.205

https://github.com/user-attachments/assets/ab28f93b-729e-4470-b97d-499a5041428b

**Comment by jhanvi03** [comment]
Re-opening the issue as moving from Secondary to Primary command throws compilation error
Tested with:
Sdk/template: 6.4.0-dev.43
TFM: Desktop
IDE: VS

https://github.com/user-attachments/assets/8de16692-2007-4dc7-957e-20025c986c80

**Comment by nickrandolph** [comment]
@jhanvi03 you dragged the button inside the other button. This is only possible because you didn't set the content on the button. Can you try this again with setting content on the buttons when you create them

**Comment by rajamatt** [comment]
No errors on latest dev Uno.Sdk version 6.4.0-dev.69. Dragging from PrimaryCommand to SecondaryCommand (and vice-versa) works well and UI + Xaml updates accordingly.

---

Tested with:
Templates/SDK: 6.4.0-dev.69 (which uses Uno version 6.4.0-dev.299 and HD version 1.17.0-dev.343)
Platform(s): Desktop
IDE: VS 2022 - 17.14.16
OS: Windows
